"""Runnable end-to-end quickstart.

Registers a new agent on a target org, submits an Ed25519-signed
intent, and confirms that callers able to reach that org can resolve
the agent's profile without authentication, in under 60 seconds.

Run:

    pip install -e .                         # from the agent/ dir
    python examples/quickstart.py --chapter http://localhost:8080

The script generates a fresh Ed25519 keypair on every run, picks a
unique agent_id (so re-running doesn't collide), registers, submits
one signed intent, prints the unauthenticated profile URL, and exits.

It does NOT persist the keypair anywhere — for a real install run
``community-member`` instead. This is the demo, not the install.
"""

from __future__ import annotations

import argparse
import secrets
import sys
import time


def _step(n: int, total: int, msg: str) -> None:
    print(f"\n[{n}/{total}] {msg}")


def _ok(msg: str) -> None:
    print(f"      ✓ {msg}")


def _info(msg: str) -> None:
    print(f"      → {msg}")


def _fail(msg: str, *, exit_code: int = 1) -> None:
    print(f"\n      ✗ {msg}", file=sys.stderr)
    sys.exit(exit_code)


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(
        description=(
            "Demo: register a sovereign agent with an org, submit an "
            "Ed25519-signed intent, and verify its unauthenticated profile."
        )
    )
    ap.add_argument(
        "--chapter",
        required=True,
        help="Org URL (required; for a local org, use http://localhost:8080).",
    )
    ap.add_argument(
        "--name",
        default=None,
        help="Display name (default: a generated one like 'demo-agent-a4f9c').",
    )
    args = ap.parse_args(argv)

    chapter_url = args.chapter.rstrip("/")
    print(f"Quickstart against org: {chapter_url}")
    total = 6

    # ── 1. Health-check the chapter first so a typo'd URL fails fast ──
    _step(1, total, "Probe the org")
    try:
        import httpx

        health = httpx.get(f"{chapter_url}/health", timeout=10.0).json()
        version = httpx.get(f"{chapter_url}/api/version", timeout=10.0).json()
    except Exception as e:
        _fail(f"Could not reach org at {chapter_url}: {type(e).__name__}: {e}")

    chapter_id = health.get("agent_id", "?")
    chapter_slug = health.get("slug", "?")
    member_count = health.get("members", "?")
    _ok(f"Org responds: {chapter_id} (slug: {chapter_slug}, {member_count} members)")
    _info(f"Protocol versions accepted: {version.get('protocol_versions', [])}")
    _info(f"A2UI versions emit: {version.get('a2ui_versions', [])}")

    # ── 2. Generate a fresh sovereign Ed25519 identity ───────────────
    _step(2, total, "Generate Ed25519 keypair (this happens locally; key never leaves)")
    try:
        from community_member import auth, crypto
    except ImportError as e:
        _fail(f"community_member not importable ({e}). Did you run `pip install -e .` from the agent/ directory first?")
    kp = crypto.generate_ed25519_keypair()
    private_key = kp["private_key"]
    public_key = kp["public_key"]
    auth.init_keys(
        private_key_b64=private_key,
        public_key_b64=public_key,
        scheme="ed25519",
    )
    _ok(f"Public key (base64, first 16 chars): {public_key[:16]}…")
    did = crypto.build_did_key(public_key)
    _ok(f"did:key derived: {did[:32]}…")

    # ── 3. Pick a unique agent_id ────────────────────────────────────
    _step(3, total, "Pick a unique agent_id for this demo run")
    nonce = secrets.token_hex(3)  # 6 hex chars — collision-resistant for a demo
    agent_id = f"demo-agent-{nonce}"
    name = args.name or agent_id
    _ok(f"agent_id = {agent_id}")

    # ── 4. Construct the A2A client + register ───────────────────────
    _step(4, total, "Register with the org (first contact binds your public key)")
    from community_member.a2a_client import A2AClient

    client = A2AClient(
        chapter_url,
        agent_id=agent_id,
        private_key=private_key,
        public_key=public_key,
    )
    result = client.join_chapter(
        agent_id=agent_id,
        name=name,
        description="Quickstart demo agent — generated by examples/quickstart.py",
        skills=["python", "demo", "quickstart"],
        origin="sovereign",
    )
    if not result.get("registered"):
        _fail(f"Registration failed: {result}")
    _ok(f"Registered as {result.get('agent_id')} on {result.get('chapter')}")
    _ok(f"Origin recorded as: {result.get('origin')} (sovereign trust tier)")

    # ── 5. Submit a signed intent ────────────────────────────────────
    _step(5, total, "Submit a signed intent (org verifies the Ed25519 signature)")
    try:
        intent_result = client.submit_intent(
            agent_id=agent_id,
            text="Looking to demo cross-org federation",
            tags=["demo", "federation"],
        )
    except Exception as e:
        _fail(f"submit_intent crashed: {type(e).__name__}: {e}")
    if intent_result.get("error"):
        _fail(f"Org rejected the signed intent: {intent_result['error']}\n      → Full response: {intent_result}")
    _ok(f"Intent recorded: {intent_result.get('id') or intent_result.get('intent_id') or '(success)'}")

    # ── 6. Verify the open profile + signed member listing ──────────
    _step(6, total, "Confirm registration (your profile is private until you publish it)")
    # The per-agent profile is CONSENT-GATED: it serves a member who opted in
    # through POST /api/me/listing, and 404s for one who has not — which is
    # every member by default, including this one. This step used to fetch the
    # profile and report "resolves without authentication", which was true and
    # is no longer: a new agent has no public profile until its owner says so.
    #
    # Reporting the 404 as success would be worse than not checking, so the
    # check is what it can honestly be: the org knows you, read back over a
    # signed call that proves it is YOU asking.
    profile_state = "private (not published)"
    for _attempt in range(5):
        time.sleep(1.5)
        listed = client.api_call("GET", "/api/members").get("members") or []
        if any(m.get("agent_id") == agent_id for m in listed):
            _ok(f"Org confirms your registration over a signed read ({len(listed)} members)")
            break
    else:
        _info("Org has not surfaced the member yet — it may need another second.")

    # Show that neither read surface is open to a stranger: the bulk directory
    # requires a signature, and the per-agent profile is gated on the member's
    # own consent. Both matter — a gated directory beside a per-id surface that
    # answered for everyone would have left the org enumerable one id at a time.
    anon = httpx.get(f"{chapter_url}/api/agents/{agent_id}/profile", timeout=15)
    if anon.status_code == 404:
        _ok("Your profile is private: an unauthenticated caller cannot read it")
    else:
        _info(f"Unexpected: profile returned {anon.status_code} to an anonymous caller")

    # ── Final summary ────────────────────────────────────────────────
    profile_url = f"{chapter_url}/api/agents/{agent_id}/profile"
    print()
    print("─" * 60)
    print("DONE. Your agent is registered on this org.")
    print()
    print(f"  agent_id:          {agent_id}")
    print(f"  did:key:           {did}")
    print(f"  org:               {chapter_id}")
    print(f"  profile:           {profile_url}")
    print(f"                     {profile_state} — publish it with a signed")
    print('                     POST /api/me/listing {"listed": true}')
    print()
    print(
        "Note: this demo does NOT persist your keypair. To install a "
        "permanent agent that survives across sessions, run the wizard:"
    )
    print()
    print("    community-member")
    print()
    print(
        "The wizard saves keys to your tiered keystore (OS keychain → "
        "passphrase → device fingerprint), generates a BIP39 recovery "
        "phrase, and starts the agent with a local dashboard at "
        "http://localhost:7777."
    )


if __name__ == "__main__":
    main()
